// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: k5kJvsPRoLouUiqztENREe
// Component: kwhioOgxT1
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_front_end.module.css"; // plasmic-import: k5kJvsPRoLouUiqztENREe/projectcss
import * as sty from "./PlasmicSingUpButton.module.css"; // plasmic-import: kwhioOgxT1/css

export const PlasmicSingUpButton__VariantProps = new Array();

export const PlasmicSingUpButton__ArgProps = new Array();

function PlasmicSingUpButton__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"sing up"}
    </button>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSingUpButton__ArgProps,
      internalVariantPropNames: PlasmicSingUpButton__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicSingUpButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSingUpButton";
  } else {
    func.displayName = `PlasmicSingUpButton.${nodeName}`;
  }
  return func;
}

export const PlasmicSingUpButton = Object.assign(
  // Top-level PlasmicSingUpButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicSingUpButton
    internalVariantProps: PlasmicSingUpButton__VariantProps,
    internalArgProps: PlasmicSingUpButton__ArgProps
  }
);

export default PlasmicSingUpButton;
/* prettier-ignore-end */
