// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: k5kJvsPRoLouUiqztENREe
// Component: GlgkEs0yZx
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_front_end.module.css"; // plasmic-import: k5kJvsPRoLouUiqztENREe/projectcss
import * as sty from "./PlasmicLoginButton.module.css"; // plasmic-import: GlgkEs0yZx/css

export const PlasmicLoginButton__VariantProps = new Array();

export const PlasmicLoginButton__ArgProps = new Array();

function PlasmicLoginButton__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.button,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"login"}
    </button>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginButton__ArgProps,
      internalVariantPropNames: PlasmicLoginButton__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicLoginButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginButton";
  } else {
    func.displayName = `PlasmicLoginButton.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginButton = Object.assign(
  // Top-level PlasmicLoginButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLoginButton
    internalVariantProps: PlasmicLoginButton__VariantProps,
    internalArgProps: PlasmicLoginButton__ArgProps
  }
);

export default PlasmicLoginButton;
/* prettier-ignore-end */
